rebuild

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -4,7 +4,7 @@
 
 # Parse cmd arguments
 
-SRC_BRANCH="master"
+SRC_BRANCH="main"
 DEPLOY_BRANCH="gh-pages"
 
 USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push]"
@@ -18,8 +18,6 @@ while [[ $# > 0 ]]; do
         exit 0
         ;;
         -u|--user)
-        SRC_BRANCH="source"
-        DEPLOY_BRANCH="master"
         ;;
         -s|--src)
         SRC_BRANCH="$2"
@@ -59,13 +57,13 @@ then
 fi
 
 # Check if there are any uncommitted changes
-# if ! git diff-index --quiet HEAD --; then
-#     echo "Changes to the following files are uncommitted:"
-#     git diff-index --name-only HEAD --
-#     echo "Please commit the changes before proceeding."
-#     echo "Aborting."
-#     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-# fi
+if ! git diff-index --quiet HEAD --; then
+    echo "Changes to the following files are uncommitted:"
+    git diff-index --name-only HEAD --
+    echo "Please commit the changes before proceeding."
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
 
 # Check if there are any untracked files
 if ! test -z "$(git ls-files --exclude-standard --others)"; then
@@ -91,14 +89,22 @@ then
 fi
 git checkout -b $DEPLOY_BRANCH
 
+# Export JEKYLL_ENV=production
+export JEKYLL_ENV=production
+
 # Build site
-bundle update uri
 bundle exec jekyll build
+
+# Purge unused css
+purgecss -c purgecss.config.js
 
 # Delete and move files
 find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
 mv _site/* .
 rm -R _site/
+
+# Create `.nojekyll` file (bypass GitHub Pages Jekyll processing)
+touch .nojekyll
 
 # Push to DEPLOY_BRANCH
 git add -fA
